# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(800, 600)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout_main.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_main.setSpacing(10)
        self.verticalLayout_main.setObjectName("verticalLayout_main")

        self.groupBox_files = QtWidgets.QGroupBox(MainForm)
        self.groupBox_files.setObjectName("groupBox_files")
        self.verticalLayout_group = QtWidgets.QVBoxLayout(self.groupBox_files)
        self.verticalLayout_group.setObjectName("verticalLayout_group")

        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")

        self.btn_add_files = QtWidgets.QPushButton(self.groupBox_files)
        self.btn_add_files.setObjectName("btn_add_files")
        self.horizontalLayout_buttons.addWidget(self.btn_add_files)

        self.btn_delete_selected = QtWidgets.QPushButton(self.groupBox_files)
        self.btn_delete_selected.setObjectName("btn_delete_selected")
        self.horizontalLayout_buttons.addWidget(self.btn_delete_selected)

        self.btn_clear_list = QtWidgets.QPushButton(self.groupBox_files)
        self.btn_clear_list.setObjectName("btn_clear_list")
        self.horizontalLayout_buttons.addWidget(self.btn_clear_list)

        spacerItem_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem_left)
        self.verticalLayout_group.addLayout(self.horizontalLayout_buttons)

        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_files)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(36)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setStyleSheet("""
            QTableWidget {
                border: 1px solid #dcdfe6;
                border-radius: 8px;
                background-color: #fafafa;
                padding: 4px;
                gridline-color: #e4e7ed;
            }
            QTableWidget::item {
                padding: 6px 12px;
                border: none;
                border-bottom: 1px solid #e4e7ed;
            }
            QTableWidget::item:selected {
                background-color: #409eff;
                color: #ffffff;
            }
            QHeaderView::section {
                background-color: #409eff;
                color: #ffffff;
                padding: 6px 12px;
                border: none;
                border-radius: 0;
                font-weight: bold;
            }
            QHeaderView::section:first {
                border-top-left-radius: 8px;
            }
            QHeaderView::section:last {
                border-top-right-radius: 8px;
            }
            QScrollBar:vertical {
                border: none;
                width: 8px;
                background: #f5f7fa;
            }
            QScrollBar::handle:vertical {
                background: #c0c4cc;
                border-radius: 4px;
                min-height: 30px;
            }
            QScrollBar::handle:vertical:hover {
                background: #909399;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
        """)
        self.verticalLayout_group.addWidget(self.tableWidget)

        self.verticalLayout_main.addWidget(self.groupBox_files)

        self.tabWidget = QtWidgets.QTabWidget(MainForm)
        self.tabWidget.setObjectName("tabWidget")

        self.tab_transcode = QtWidgets.QWidget()
        self.tab_transcode.setObjectName("tab_transcode")
        self.verticalLayout_transcode = QtWidgets.QVBoxLayout(self.tab_transcode)
        self.verticalLayout_transcode.setObjectName("verticalLayout_transcode")

        self.horizontalLayout_format = QtWidgets.QHBoxLayout()
        self.horizontalLayout_format.setObjectName("horizontalLayout_format")

        self.label_source = QtWidgets.QLabel(self.tab_transcode)
        self.label_source.setObjectName("label_source")
        self.horizontalLayout_format.addWidget(self.label_source)

        self.label_source_format = QtWidgets.QLabel(self.tab_transcode)
        self.label_source_format.setObjectName("label_source_format")
        self.label_source_format.setStyleSheet("color: #0066cc; font-weight: bold;")
        self.horizontalLayout_format.addWidget(self.label_source_format)

        self.label_arrow = QtWidgets.QLabel(self.tab_transcode)
        self.label_arrow.setObjectName("label_arrow")
        self.horizontalLayout_format.addWidget(self.label_arrow)

        self.label_target = QtWidgets.QLabel(self.tab_transcode)
        self.label_target.setObjectName("label_target")
        self.horizontalLayout_format.addWidget(self.label_target)

        self.comboBox_target = QtWidgets.QComboBox(self.tab_transcode)
        self.comboBox_target.setObjectName("comboBox_target")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.comboBox_target.addItem("")
        self.horizontalLayout_format.addWidget(self.comboBox_target)

        spacerItem_format = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_format.addItem(spacerItem_format)
        self.verticalLayout_transcode.addLayout(self.horizontalLayout_format)

        self.horizontalLayout_output = QtWidgets.QHBoxLayout()
        self.horizontalLayout_output.setObjectName("horizontalLayout_output")
        self.label_output = QtWidgets.QLabel(self.tab_transcode)
        self.label_output.setObjectName("label_output")
        self.horizontalLayout_output.addWidget(self.label_output)
        self.lineEdit_output = QtWidgets.QLineEdit(self.tab_transcode)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_output.addWidget(self.lineEdit_output)
        self.btn_browse_output = QtWidgets.QPushButton(self.tab_transcode)
        self.btn_browse_output.setObjectName("btn_browse_output")
        self.horizontalLayout_output.addWidget(self.btn_browse_output)
        self.verticalLayout_transcode.addLayout(self.horizontalLayout_output)

        spacerItem_trans = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_transcode.addItem(spacerItem_trans)
        self.tabWidget.addTab(self.tab_transcode, "")

        self.tab_fix = QtWidgets.QWidget()
        self.tab_fix.setObjectName("tab_fix")
        self.verticalLayout_fix = QtWidgets.QVBoxLayout(self.tab_fix)
        self.verticalLayout_fix.setObjectName("verticalLayout_fix")

        self.checkBox_overwrite = QtWidgets.QCheckBox(self.tab_fix)
        self.checkBox_overwrite.setChecked(True)
        self.checkBox_overwrite.setObjectName("checkBox_overwrite")
        self.verticalLayout_fix.addWidget(self.checkBox_overwrite)

        self.horizontalLayout_fix_output = QtWidgets.QHBoxLayout()
        self.horizontalLayout_fix_output.setObjectName("horizontalLayout_fix_output")
        self.label_fix_output = QtWidgets.QLabel(self.tab_fix)
        self.label_fix_output.setObjectName("label_fix_output")
        self.horizontalLayout_fix_output.addWidget(self.label_fix_output)
        self.lineEdit_fix_output = QtWidgets.QLineEdit(self.tab_fix)
        self.lineEdit_fix_output.setObjectName("lineEdit_fix_output")
        self.lineEdit_fix_output.setEnabled(False)
        self.horizontalLayout_fix_output.addWidget(self.lineEdit_fix_output)
        self.btn_browse_fix_output = QtWidgets.QPushButton(self.tab_fix)
        self.btn_browse_fix_output.setObjectName("btn_browse_fix_output")
        self.btn_browse_fix_output.setEnabled(False)
        self.horizontalLayout_fix_output.addWidget(self.btn_browse_fix_output)
        self.verticalLayout_fix.addLayout(self.horizontalLayout_fix_output)

        spacerItem_fix = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_fix.addItem(spacerItem_fix)
        self.tabWidget.addTab(self.tab_fix, "")

        self.tab_cut_intro = QtWidgets.QWidget()
        self.tab_cut_intro.setObjectName("tab_cut_intro")
        self.verticalLayout_cut_intro = QtWidgets.QVBoxLayout(self.tab_cut_intro)
        self.verticalLayout_cut_intro.setObjectName("verticalLayout_cut_intro")

        self.horizontalLayout_time = QtWidgets.QHBoxLayout()
        self.horizontalLayout_time.setObjectName("horizontalLayout_time")

        self.spinBox_hour = QtWidgets.QSpinBox(self.tab_cut_intro)
        self.spinBox_hour.setObjectName("spinBox_hour")
        self.spinBox_hour.setMinimum(0)
        self.spinBox_hour.setMaximum(23)
        self.spinBox_hour.setSuffix(" 时")
        self.horizontalLayout_time.addWidget(self.spinBox_hour)

        self.spinBox_minute = QtWidgets.QSpinBox(self.tab_cut_intro)
        self.spinBox_minute.setObjectName("spinBox_minute")
        self.spinBox_minute.setMinimum(0)
        self.spinBox_minute.setMaximum(59)
        self.spinBox_minute.setSuffix(" 分")
        self.horizontalLayout_time.addWidget(self.spinBox_minute)

        self.spinBox_second = QtWidgets.QSpinBox(self.tab_cut_intro)
        self.spinBox_second.setObjectName("spinBox_second")
        self.spinBox_second.setMinimum(0)
        self.spinBox_second.setMaximum(59)
        self.spinBox_second.setSuffix(" 秒")
        self.horizontalLayout_time.addWidget(self.spinBox_second)

        self.spinBox_frame = QtWidgets.QSpinBox(self.tab_cut_intro)
        self.spinBox_frame.setObjectName("spinBox_frame")
        self.spinBox_frame.setMinimum(0)
        self.spinBox_frame.setMaximum(999)
        self.spinBox_frame.setPrefix("0.")
        self.spinBox_frame.setSuffix(" 帧")
        self.horizontalLayout_time.addWidget(self.spinBox_frame)

        spacerItem_time = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_time.addItem(spacerItem_time)
        self.verticalLayout_cut_intro.addLayout(self.horizontalLayout_time)

        self.checkBox_cut_intro_overwrite = QtWidgets.QCheckBox(self.tab_cut_intro)
        self.checkBox_cut_intro_overwrite.setObjectName("checkBox_cut_intro_overwrite")
        self.checkBox_cut_intro_overwrite.setChecked(False)
        self.verticalLayout_cut_intro.addWidget(self.checkBox_cut_intro_overwrite)

        self.horizontalLayout_cut_output = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cut_output.setObjectName("horizontalLayout_cut_output")
        self.label_cut_output = QtWidgets.QLabel(self.tab_cut_intro)
        self.label_cut_output.setObjectName("label_cut_output")
        self.horizontalLayout_cut_output.addWidget(self.label_cut_output)
        self.lineEdit_cut_output = QtWidgets.QLineEdit(self.tab_cut_intro)
        self.lineEdit_cut_output.setObjectName("lineEdit_cut_output")
        self.horizontalLayout_cut_output.addWidget(self.lineEdit_cut_output)
        self.btn_browse_cut_output = QtWidgets.QPushButton(self.tab_cut_intro)
        self.btn_browse_cut_output.setObjectName("btn_browse_cut_output")
        self.horizontalLayout_cut_output.addWidget(self.btn_browse_cut_output)
        self.verticalLayout_cut_intro.addLayout(self.horizontalLayout_cut_output)

        spacerItem_cut = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_cut_intro.addItem(spacerItem_cut)
        self.tabWidget.addTab(self.tab_cut_intro, "")

        self.tab_merge = QtWidgets.QWidget()
        self.tab_merge.setObjectName("tab_merge")
        self.verticalLayout_merge = QtWidgets.QVBoxLayout(self.tab_merge)
        self.verticalLayout_merge.setObjectName("verticalLayout_merge")

        self.horizontalLayout_merge_format = QtWidgets.QHBoxLayout()
        self.horizontalLayout_merge_format.setObjectName("horizontalLayout_merge_format")

        self.label_merge_format = QtWidgets.QLabel(self.tab_merge)
        self.label_merge_format.setObjectName("label_merge_format")
        self.horizontalLayout_merge_format.addWidget(self.label_merge_format)

        self.comboBox_merge_format = QtWidgets.QComboBox(self.tab_merge)
        self.comboBox_merge_format.setObjectName("comboBox_merge_format")
        self.comboBox_merge_format.addItem("")
        self.comboBox_merge_format.addItem("")
        self.comboBox_merge_format.addItem("")
        self.comboBox_merge_format.addItem("")
        self.horizontalLayout_merge_format.addWidget(self.comboBox_merge_format)

        spacerItem_merge_format = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_merge_format.addItem(spacerItem_merge_format)
        self.verticalLayout_merge.addLayout(self.horizontalLayout_merge_format)

        self.horizontalLayout_merge_filename = QtWidgets.QHBoxLayout()
        self.horizontalLayout_merge_filename.setObjectName("horizontalLayout_merge_filename")

        self.label_merge_filename = QtWidgets.QLabel(self.tab_merge)
        self.label_merge_filename.setObjectName("label_merge_filename")
        self.horizontalLayout_merge_filename.addWidget(self.label_merge_filename)

        self.lineEdit_merge_filename = QtWidgets.QLineEdit(self.tab_merge)
        self.lineEdit_merge_filename.setObjectName("lineEdit_merge_filename")
        self.horizontalLayout_merge_filename.addWidget(self.lineEdit_merge_filename)

        spacerItem_merge_filename = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_merge_filename.addItem(spacerItem_merge_filename)
        self.verticalLayout_merge.addLayout(self.horizontalLayout_merge_filename)

        self.horizontalLayout_merge_output = QtWidgets.QHBoxLayout()
        self.horizontalLayout_merge_output.setObjectName("horizontalLayout_merge_output")

        self.label_merge_output = QtWidgets.QLabel(self.tab_merge)
        self.label_merge_output.setObjectName("label_merge_output")
        self.horizontalLayout_merge_output.addWidget(self.label_merge_output)

        self.lineEdit_merge_output = QtWidgets.QLineEdit(self.tab_merge)
        self.lineEdit_merge_output.setObjectName("lineEdit_merge_output")
        self.horizontalLayout_merge_output.addWidget(self.lineEdit_merge_output)

        self.btn_browse_merge_output = QtWidgets.QPushButton(self.tab_merge)
        self.btn_browse_merge_output.setObjectName("btn_browse_merge_output")
        self.horizontalLayout_merge_output.addWidget(self.btn_browse_merge_output)

        self.verticalLayout_merge.addLayout(self.horizontalLayout_merge_output)

        self.checkBox_merge_gpu = QtWidgets.QCheckBox(self.tab_merge)
        self.checkBox_merge_gpu.setObjectName("checkBox_merge_gpu")
        self.verticalLayout_merge.addWidget(self.checkBox_merge_gpu)

        spacerItem_merge = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_merge.addItem(spacerItem_merge)
        self.tabWidget.addTab(self.tab_merge, "")

        self.verticalLayout_main.addWidget(self.tabWidget)

        self.groupBox_progress = QtWidgets.QGroupBox(MainForm)
        self.groupBox_progress.setObjectName("groupBox_progress")
        self.verticalLayout_progress = QtWidgets.QVBoxLayout(self.groupBox_progress)
        self.verticalLayout_progress.setObjectName("verticalLayout_progress")

        self.label_current_progress = QtWidgets.QLabel(self.groupBox_progress)
        self.label_current_progress.setObjectName("label_current_progress")
        self.label_current_progress.setText("当前进度")
        self.verticalLayout_progress.addWidget(self.label_current_progress)

        self.progressBar = QtWidgets.QProgressBar(self.groupBox_progress)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_progress.addWidget(self.progressBar)

        self.label_total_progress = QtWidgets.QLabel(self.groupBox_progress)
        self.label_total_progress.setObjectName("label_total_progress")
        self.label_total_progress.setText("总进度")
        self.verticalLayout_progress.addWidget(self.label_total_progress)

        self.progressBar_total = QtWidgets.QProgressBar(self.groupBox_progress)
        self.progressBar_total.setProperty("value", 0)
        self.progressBar_total.setObjectName("progressBar_total")
        self.verticalLayout_progress.addWidget(self.progressBar_total)

        self.label_status = QtWidgets.QLabel(self.groupBox_progress)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_progress.addWidget(self.label_status)
        self.verticalLayout_main.addWidget(self.groupBox_progress)

        self.horizontalLayout_start = QtWidgets.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")

        spacerItem_start = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_start.addItem(spacerItem_start)

        self.btn_stop = QtWidgets.QPushButton(MainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setMinimumSize(QtCore.QSize(120, 40))
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_start.addWidget(self.btn_stop)

        self.btn_start = QtWidgets.QPushButton(MainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(120, 40))
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_start.addWidget(self.btn_start)
        self.verticalLayout_main.addLayout(self.horizontalLayout_start)

        self.retranslateUi(MainForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

        # 全局样式
        self._apply_global_stylesheet(MainForm)

    def _apply_global_stylesheet(self, MainForm):
        stylesheet = """
            QWidget {
                font-family: "Microsoft YaHei", "Segoe UI", sans-serif;
            }
            QGroupBox {
                font-weight: bold;
                border: 1px solid #dcdfe6;
                border-radius: 8px;
                margin-top: 10px;
                padding-top: 10px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 15px;
                padding: 0 5px;
                color: #409eff;
            }
            QPushButton {
                background-color: #409eff;
                color: #ffffff;
                border: none;
                border-radius: 4px;
                padding: 8px 16px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #66b1ff;
            }
            QPushButton:pressed {
                background-color: #3a8ee6;
            }
            QPushButton:disabled {
                background-color: #c0c4cc;
            }
            QPushButton[objectName="btn_delete_selected"] {
                background-color: #f56c6c;
            }
            QPushButton[objectName="btn_delete_selected"]:hover {
                background-color: #f78989;
            }
            QPushButton[objectName="btn_delete_selected"]:pressed {
                background-color: #e64242;
            }
            QPushButton[objectName="btn_clear_list"] {
                background-color: #e6a23c;
            }
            QPushButton[objectName="btn_clear_list"]:hover {
                background-color: #ebb563;
            }
            QPushButton[objectName="btn-clear_list"]:pressed {
                background-color: #cf9236;
            }
            QLineEdit {
                border: 1px solid #dcdfe6;
                border-radius: 4px;
                padding: 6px 12px;
                background-color: #ffffff;
            }
            QLineEdit:focus {
                border: 1px solid #409eff;
            }
            QLineEdit:disabled {
                background-color: #f5f7fa;
                color: #c0c4cc;
            }
            QComboBox {
                border: 1px solid #dcdfe6;
                border-radius: 4px;
                padding: 6px 12px;
                background-color: #ffffff;
            }
            QComboBox:focus {
                border: 1px solid #409eff;
            }
            QComboBox::drop-down {
                border: none;
                width: 24px;
            }
            QComboBox::down-arrow {
                image: url(down_arrow.png);
                width: 12px;
                height: 12px;
            }
            QSpinBox {
                border: 1px solid #dcdfe6;
                border-radius: 4px;
                padding: 6px 12px;
                background-color: #ffffff;
            }
            QSpinBox:focus {
                border: 1px solid #409eff;
            }
            QSpinBox::up-button, QSpinBox::down-button {
                border: none;
                width: 16px;
            }
            QCheckBox {
                spacing: 8px;
            }
            QCheckBox::indicator {
                width: 18px;
                height: 18px;
                border-radius: 4px;
                border: 2px solid #dcdfe6;
            }
            QCheckBox::indicator:checked {
                background-color: #409eff;
                border-color: #409eff;
            }
            QTabWidget::pane {
                border: 1px solid #dcdfe6;
                border-radius: 8px;
                background-color: #ffffff;
            }
            QTabBar::tab {
                background-color: #f5f7fa;
                color: #606266;
                padding: 10px 20px;
                border-top-left-radius: 8px;
                border-top-right-radius: 8px;
                margin-right: 2px;
            }
            QTabBar::tab:selected {
                background-color: #ffffff;
                color: #409eff;
                font-weight: bold;
            }
            QTabBar::tab:hover {
                background-color: #ecf5ff;
            }
            QProgressBar {
                border: none;
                border-radius: 6px;
                background-color: #e4e7ed;
                height: 12px;
                text-align: center;
            }
            QProgressBar::chunk {
                background-color: #409eff;
                border-radius: 6px;
            }
            QLabel {
                color: #303133;
            }
            QScrollBar:vertical {
                border: none;
                width: 8px;
                background: #f5f7fa;
                margin: 0;
            }
            QScrollBar::handle:vertical {
                background: #c0c4cc;
                border-radius: 4px;
                min-height: 30px;
            }
            QScrollBar::handle:vertical:hover {
                background: #909399;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
            QScrollBar:horizontal {
                border: none;
                height: 8px;
                background: #f5f7fa;
                margin: 0;
            }
            QScrollBar::handle:horizontal {
                background: #c0c4cc;
                border-radius: 4px;
                min-width: 30px;
            }
            QScrollBar::handle:horizontal:hover {
                background: #909399;
            }
            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {
                width: 0px;
            }
        """
        MainForm.setStyleSheet(stylesheet)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "视频处理工具"))
        self.groupBox_files.setTitle(_translate("MainForm", "视频文件 (可拖拽添加)"))
        self.btn_add_files.setText(_translate("MainForm", "添加文件"))
        self.btn_delete_selected.setText(_translate("MainForm", "删除选中"))
        self.btn_clear_list.setText(_translate("MainForm", "清空列表"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainForm", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainForm", "状态"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainForm", "路径"))
        self.label_source.setText(_translate("MainForm", "源格式:"))
        self.label_source_format.setText(_translate("MainForm", "未选择"))
        self.label_arrow.setText(_translate("MainForm", "→"))
        self.label_target.setText(_translate("MainForm", "目标格式:"))
        self.comboBox_target.setItemText(0, _translate("MainForm", "MP4"))
        self.comboBox_target.setItemText(1, _translate("MainForm", "TS"))
        self.comboBox_target.setItemText(2, _translate("MainForm", "FLV"))
        self.comboBox_target.setItemText(3, _translate("MainForm", "MKV"))
        self.label_output.setText(_translate("MainForm", "输出文件夹:"))
        self.btn_browse_output.setText(_translate("MainForm", "浏览..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_transcode), _translate("MainForm", "转码"))
        self.checkBox_overwrite.setText(_translate("MainForm", "覆盖源文件"))
        self.label_fix_output.setText(_translate("MainForm", "输出文件夹:"))
        self.btn_browse_fix_output.setText(_translate("MainForm", "浏览..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fix), _translate("MainForm", "修复MP4索引"))
        self.checkBox_cut_intro_overwrite.setText(_translate("MainForm", "覆盖源文件"))
        self.label_cut_output.setText(_translate("MainForm", "输出文件夹:"))
        self.btn_browse_cut_output.setText(_translate("MainForm", "浏览..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cut_intro), _translate("MainForm", "去除片头"))
        self.label_merge_format.setText(_translate("MainForm", "输出格式:"))
        self.comboBox_merge_format.setItemText(0, _translate("MainForm", "MP4"))
        self.comboBox_merge_format.setItemText(1, _translate("MainForm", "TS"))
        self.comboBox_merge_format.setItemText(2, _translate("MainForm", "FLV"))
        self.comboBox_merge_format.setItemText(3, _translate("MainForm", "MKV"))
        self.label_merge_filename.setText(_translate("MainForm", "输出文件名:"))
        self.lineEdit_merge_filename.setText(_translate("MainForm", "合并视频"))
        self.label_merge_output.setText(_translate("MainForm", "输出文件夹:"))
        self.btn_browse_merge_output.setText(_translate("MainForm", "浏览..."))
        self.checkBox_merge_gpu.setText(_translate("MainForm", "使用NVIDIA GPU加速（需要NVIDIA显卡）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_merge), _translate("MainForm", "合并视频"))
        self.groupBox_progress.setTitle(_translate("MainForm", "处理进度"))
        self.label_status.setText(_translate("MainForm", "就绪"))
        self.btn_start.setText(_translate("MainForm", "开始处理"))
        self.btn_stop.setText(_translate("MainForm", "停止任务"))
